### ISSUE TITLE
Have an own file/ticket and call it Solution here

### ISSUE THREAD

**Issue by andreas-roehler** [winitzki/sofp-solutions#5]
Suggest to create an own file for every exercise here. Possibly an own ticket, keeping discussion and alternatives, to close when done. Also suggest calling this a solution - people will figure out, there must be a task for every solution elsewhere.

**Comment by winitzki** [comment]
I prefer to follow standard practices and write tests rather than individual files that you load by hand via `:load`.

We can have one test class per exercise and certainly we can call it a "Solution_1_6_1_1.scala" or something like that.
