### ISSUE TITLE
Hints for the solution of exercise 2.2.6.3

### ISSUE THREAD

**Issue by winitzki** [winitzki/sofp-solutions#63]
@andreas-roehler  Here are some hints for solution2.2.6.3

The solution should not use `var`.

I suggest that type `Acc` should include the current value of the index as well as the resulting sequence.

You wrote a loop that works. The loop goes like this:

-   Initially, `counter = -1` and the sequence is empty.

-   At each step, `counter = counter + 1` and the sequence is modified as well.

To reformulate this as a fold, you try writing code like this:

```scala
def zipWithIndex[A](xs: Seq[A]): Seq[(A, Int)] = {
   type Acc = ???
   val init : Acc = ???
   val update: (Acc, A) => Acc = { case (previousAcc, x) =>  ??? }
   xs.foldLeft(init)(update)
}
```

The type `Acc` must hold all data that is being updated by the loop. In your case, this is both the counter and the sequence.
So, the accumulator must be a tuple: `Acc = (Int, Seq[A])`.
Now you can rewrite your loop as a `foldLeft`. No more `var` anywhere.
You just need to write `init` and `update`.

The function `update` will look like this: `{ case ((previousCounter, previousSeq), x) =>  (newCounter, newSeq) }` where you need to write the correct expressions for `newCounter` and `newSeq`.

**Comment by andreas-roehler** [comment]
Close this?
