### ISSUE TITLE
Can't load Exercises_2_1_7.scala

### ISSUE THREAD

**Issue by andreas-roehler** [winitzki/sofp-solutions#8]
Get errors from :load in scala-shell:

:load Exercises_2_1_7.scala
Loading Exercises_2_1_7.scala...
Exercises_2_1_7.scala:1: error: illegal start of definition
package sofp.unit
^
Exercises_2_1_7.scala:11: error: object eed3si9n is not a member of package com
       import com.eed3si9n.expecty.Expecty.expect
                  ^
Exercises_2_1_7.scala:11: error: not found: value munit
       import munit.FunSuite
              ^
Exercises_2_1_7.scala:12: error: not found: type FunSuite
       class Exercises_2_1_7 extends FunSuite {
                                     ^
Exercises_2_1_7.scala:14: error: not found: value test
         test("Exercise 2.1.7.1") {
       
... and many more

**Comment by andreas-roehler** [comment]
Suggest to de-couple that stuff.

**Comment by winitzki** [comment]
These files are not designed for `:load` command. They are test files that can be run via `sbt test`.

**Comment by winitzki** [comment]
> Suggest to de-couple that stuff.
@andreas-roehler 
 Done. Now you can add your solutions to the `worksheets/` subdirectory and sbt will ignore them. I moved your solution 1.6 .1.1 to `worksheets/` and the tests pass now.
